server:
  servlet:
    context-path: /
  port: 7080

webdriver:
  chrome:
    path: /Users/admin/Downloads/chromedriver
  firefox:
    path: /Users/admin/Workspace/geckodriver
instaservice:
  filePath: /Users/admin/Workspace/instaservice/Files/

file:
  path: /Users/admin/Workspace/Files/
