
spring:
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/instafame
    username: postgres
    password: asdasdsa
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    initialization-mode: always
