
spring:
  datasource:
    url: jdbc:p6spy:postgresql://${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    initialization-mode: always
